#!/bin/bash

echo "=== MiniShell Test Examples ==="
echo ""
echo "Compile the shell first with: make"
echo "Then run: ./minishell"
echo ""
echo "Test commands to try:"
echo ""
echo "1. Basic commands:"
echo "   ls -la"
echo "   pwd"
echo "   whoami"
echo ""
echo "2. Built-in commands:"
echo "   cd /tmp"
echo "   pwd"
echo "   cd -"
echo "   help"
echo "   exit"
echo ""
echo "3. Redirection tests:"
echo "   ls -la > test_output.txt"
echo "   cat < test_output.txt"
echo "   echo 'Hello World' >> test_output.txt"
echo "   cat test_output.txt"
echo ""
echo "4. Pipe tests:"
echo "   ls -la | grep '.cpp'"
echo "   ps aux | grep minishell"
echo "   cat test_output.txt | wc -l"
echo "   echo 'line1\nline2\nline3' | grep line"
echo ""
echo "5. Background process tests:"
echo "   sleep 5 &"
echo "   ping -c 3 google.com > ping.txt &"
echo "   (wait a few seconds and see completion messages)"
echo ""
echo "6. Complex combinations:"
echo "   ls -la | grep '.txt' | wc -l > count.txt"
echo "   cat count.txt"
echo ""
echo "7. Signal handling:"
echo "   (Press Ctrl+C during command - should show prompt)"
echo "   (Press Ctrl+Z during command - should show prompt)"
echo ""
echo "8. Error handling:"
echo "   nonexistentcommand"
echo "   cd /nonexistent/directory"
echo "   ls > /readonly/file.txt"
echo ""
echo "Clean up test files:"
echo "   rm -f test_output.txt ping.txt count.txt"
